### ISSUE TITLE
filename 'apps/org.fedorahosted.freeotp/sp/tokens.xml' not found

### ISSUE THREAD

**Issue by e-minguez** [raphiz/freeotp-backup#2]
Fedora 32 x86_64:

```
$ git clone git@github.com:raphiz/freeotp-backup.git
$ cd freeotp-backup/
$ python -m venv venv
$ source venv/bin/activate
$ pip install -r requirements.txt
$ adb backup -f freeotp-backup.ab -apk org.fedorahosted.freeotp
$ python3 backup_freetop_codes.py freeotp-backup.ab 
Traceback (most recent call last):
  File "backup_freetop_codes.py", line 18, in <module>
    extracted = tf.extractfile('apps/org.fedorahosted.freeotp/sp/tokens.xml')
  File "/usr/lib64/python3.8/tarfile.py", line 2093, in extractfile
    tarinfo = self.getmember(member)
  File "/usr/lib64/python3.8/tarfile.py", line 1780, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'apps/org.fedorahosted.freeotp/sp/tokens.xml' not found"
```

**Comment by e-minguez** [comment]
Actually it seems the backup doesn't longer works :( https://github.com/freeotp/freeotp-android/issues/196#issuecomment-441633608

**Comment by raphiz** [comment]
Thanks for the report! I will have a look at [andOTP](https://github.com/andOTP/andOTP), as it has first-class support for backups using PGP. This sounds like a better solution from both a security and usability standpoint. I suggest you find an alternative as well.  

I will probably archive this repo if this, or a similar app, works as expected.
